---
kind: pipeline
type: docker
name: clamav

steps:
  - name: generate_tags
    image: alpine:latest
    commands:
      - echo -n "date:$(date +%Y-%m-%d),build:${DRONE_BUILD_NUMBER}" > .tags

  - name: clamav
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav
      tags:
        - latest
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=${DRONE_STAGE_NAME}
