---
kind: pipeline
type: docker
name: clamav

steps:
  - name: generate_tags
    image: alpine:latest
    commands:
      - ash drone_tags_helper.sh

  - name: clamav
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    when:
      branch:
        - master


  - name: clamav_eval
    image: plugins/docker
    settings:
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    dry_run: true
    when:
      event:
        - pull_request
        - push
      branch:
        exclude:
          - master
