---
kind: pipeline
type: docker
name: clamav

steps:
  - name: generate_tags
    image: alpine:latest
    commands:
      - ash drone_tags_helper.sh

  # build + push image to docker production
  - name: clamav_production
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  # build + push image to docker testing (for eval)
  - name: clamav_testing
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav_testing
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    when:
      event:
        - pull_request

  # build image but do not push (for testing)
  - name: clamav_dev
    image: plugins/docker
    settings:
      dry_run: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav_testing
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    when:
      event:
        - push
