---
kind: pipeline
type: docker
name: clamav

steps:
  - name: clamav
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav
      tags:
        - buildnumber-${DRONE_BUILD_NUMBER}
        - builddate-${BUILD_DATE}
        - latest
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=${DRONE_STEP_NAME}
