---
kind: pipeline
type: docker
name: clamav

steps:
  - name: generate_tags
    image: alpine:latest
    commands:
      - echo -n "builddate-$(date +%Y-%m-%d)" > .tags
      - echo -n ",build-${DRONE_BUILD_NUMBER}" >> .tags
      - echo -n ",latest" >> .tags
      - ls -alhtr

  - name: clamav
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kriegerse/clamav
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    when:
      branch:
        - master


  - name: clamav_eval
    image: plugins/docker
    settings:
      dockerfile: clamav/Dockerfile
      build_args:
        - FS_BASE=clamav
    dry_run: true
    when:
      event:
        - pull_request
        - push
      branch:
        exclude:
          - master
