---
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - prepare
  - build
  - test
  - publish

before_script:
  - docker login -u $docker_username -p "$docker_password" $docker_registry

include:
  - local: '/clamav/gitlab-clamav.yml'
