---
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
#  - test
#  - release

before_script:
  - docker login -u $docker_username -p "$docker_password" $docker_registry

build:
  stage: build
  script:
    - docker build --network host -f clamav/Dockerfile
      --build-arg FS_BASE=clamav
      -t clamav-stage:gitlabtest .
    - docker image ls
    # - docker push $docker_username/clamav-stage:gitlabtest

    # - docker build --pull clamav/Dockerfile
    # - docker push $TEST_IMAGE
