---
image: docker:latest
services:
  - docker:dind

stages:
  - build
#  - test
#  - release

before_script:
  - docker login -u $docker_username -p "$docker_password" $docker_registry

build:
  stage: build
  script:
    - docker info
    - cat /etc/resolv.conf
    - curl -vvv -k -L
      http://download.opensuse.org/repositories/security/
      openSUSE_Leap_15.1/security.repo
    - docker build -f clamav/Dockerfile --build-arg FS_BASE=clamav
      -t clamav-stage:latest .
    - docker push clamav-stage:gitlabtest

    # - docker build --pull clamav/Dockerfile
    # - docker push $TEST_IMAGE
