---
image: docker:latest
services:
  - docker:dind

stages:
  - build
#  - test
#  - release

before_script:
  - docker login -u $docker_username -p "$docker_password" $docker_registry

build:
  stage: build
  script:
    - docker info
    - cat /etc/resolv.conf
    - nslookup download.opensuse.org ; true
    - nslookup google.de 8.8.8.8 ; true
    - docker build -f clamav/Dockerfile --build-arg FS_BASE=clamav
      -t clamav-stage:latest . ; true
    - docker push clamav-stage:gitlabtest ; true

    # - docker build --pull clamav/Dockerfile
    # - docker push $TEST_IMAGE
