---
image: docker:latest
services:
  - docker:dind

stages:
  - build
#  - test
#  - release

before_script:
  - docker login -u $docker_username -p "$docker_password" $docker_registry

build:
  stage: build
  script:
    # - docker info
    # - ls -alhtr /etc/resolv.conf
    # - cat /etc/resolv.conf
    # - nc -nvz -w 5 1.1.1.1 53
    # - nslookup download.opensuse.org 1.1.1.1
    # - cp -a /etc/resolv.conf /etc/resolv.conf_orig
    # - sed -i "" -e 's/^nameserver.*$/nameserver 1.1.1.1/g' /etc/resolv.conf
    # - nslookup download.opensuse.org
    - docker build --network host -f clamav/Dockerfile
      --build-arg FS_BASE=clamav
      -t clamav-stage:latest .
    - docker push clamav-stage:gitlabtest ; true

    # - docker build --pull clamav/Dockerfile
    # - docker push $TEST_IMAGE
